function draw_crack_opening_field(xdata1, ydata1, zdata1, cdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1, cdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 03-Jun-2025 01:38:51

% Create figure
figure1 = figure('WindowState','maximized','Color',[1 1 1]);
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,cdata1,'Parent',axes1,'FaceLighting','gouraud',...
    'FaceColor','interp',...
    'EdgeColor','none');

% Create light
light('Parent',axes1,...
    'Position',[0.405765305886014 -0.382109607903595 0.209488714392275],...
    'Style','local');

% Create zlabel
zlabel('X (m)','Interpreter','tex');

% Create ylabel
ylabel('Y (m)','Interpreter','tex');

% Create xlabel
xlabel('Z (m)','Interpreter','tex');

axis(axes1,'tight');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'CLim',[0 180],'CameraUpVector',[0 0 1],'DataAspectRatio',[1 1 1],...
    'FontSize',32,'LineWidth',1.5);
% Create colorbar
colorbar(axes1,'Position',...
    [0.648511343804539 0.127212847753107 0.0111692844677138 0.784243134188202],...
    'FontSize',32);

